### ISSUE TITLE
Can not find any documentation about the Level::100 hint

### ISSUE THREAD

**Issue by eHanseJoerg** [tkock/flowchartwiki#4]
In [mediawiki.org/wiki/extensions](https://www.mediawiki.org/wiki/Extension:FlowChartWiki), there is a small sentence about the meaning of „Level“.

But it does not state how to use the Level tag, what integers are allowed and what results can be expected. Couldn’t find anything in the readme here, either. Care to elaborate?

**Comment by tkock** [comment]
Hi Jörg !
The documentation is quite brief - indeed :-)
Background: Graphviz - the diagramming software behind FlowchartWiki - is quite sophisticated to create optimized graphs - from its own graph algo perspective. The graphs created by GraphViz may not look like what you would like them to be in a process or flow charting environment. All we can do is give some hints to graphviz on positioning items on a (magical) horizontal line. This is achieved by the (optional) "Level" Tag.
All Items tagged with the same Level Tag should be placed on the same (invisible) horizontal line by GraphViz.
You are free to use it.
By not using it, your chart may look quite different every time you add or remove an item to it - because of GraphViz´ magic in optimizing the placement.

* Level::1010 - Steps with same level are in same line in graph.".
* From http://www.flowchartwiki.org/wiki/index.php/DecisionMaking (well hidden :-) )
"Level::0995: The automatic flowcharting needs some hints on where to place the process step into the diagram. We are using a line number system. All Process steps with the same line number will show up on the same line in the diagram. Higher line numbers will be displayed on a lower level. That´s the only option you have to modify the diagram - sorry, no more hours spent with beefing up your slideshows..."

Hope this helps.

**Comment by eHanseJoerg** [comment]
Hello Thomas,


yes this indeed helps a lot. Thanks a lot and have a nice weekend!


Brgds
Jörg


Am 10.08.2017 um 19:15 schrieb Thomas Kock:
