### ISSUE TITLE
test passed and failed.

### ISSUE THREAD

**Issue by Nickcarter74** [tkock/flowchartwiki#6]
![image](https://user-images.githubusercontent.com/262088/31954065-d85169ae-b8e4-11e7-8901-90abdd330c8b.png)

As you can see, on the test page i have this unexpected "ModelType::Draw" on the screen.

On test1 page i got this:
![image](https://user-images.githubusercontent.com/262088/31954150-1761cf08-b8e5-11e7-9fae-059749309d6a.png)

and on test2 this:

![image](https://user-images.githubusercontent.com/262088/31954186-2c595430-b8e5-11e7-83da-a354f71b28db.png)

**Comment by tkock** [comment]
This is expected behavior. Please see the test pages on flowchartwiki org (http://www.flowchartwiki.org/wiki/index.php/Test1). 
Also the hint given in http://www.flowchartwiki.org/wiki/index.php/EnterProcesses:
""Positioning of the Tags:
You may want to place all the FlowchartWiki related tags (like "NextStep::Maintenance", "Type::Rect_Green", "Level::1030" etc.) to the end of the page, if your users are disturbed by the tags showing up in the middle of the text. ""
